-- 027_recruitment_fall_2026.sql
-- Fall 2026 exec hiring round (David, 2026-09-02): VP Marketing + PM, both
-- public, open Sept 5 2026 00:00 EDT, close end of day Sept 11 EDT.
--
-- Why new rows instead of re-dating May's: applications has
-- UNIQUE(user_id, position_id), so reusing a row would block every May
-- applicant from reapplying, and the admin board has no round filter, so
-- May and fall applicants would share a kanban with no way to tell them
-- apart. Retiring the May rows under a suffixed slug keeps their
-- applications intact and visibly labelled, and frees the clean slugs
-- (which ApplicationForm's attachment special-casing and ROLE_CONTENT key
-- on) for the fall rows.
--
-- VP Marketing copy is the "Polished" Video & Content posting (Hiring
-- Descriptions doc, 2026-09-02). PM essays are placeholders; David is
-- supplying the fall questions. Both fall rows land INACTIVE (David, 2026-09-05: hold the
-- round until the real questions are in). scripts/_apply-fall-2026-essays.mjs
-- writes the questions and flips is_active on; do not edit this file once
-- it has been applied.
--
-- Idempotent: safe to re-run.

BEGIN;

-- 1. Everything from May goes dark.
UPDATE public.positions SET is_active = false;

-- 2. Retire the May VP Marketing row under a suffixed slug so its
--    applications stay attached and the admin role filter reads clearly.
UPDATE public.positions
SET slug = 'vp-marketing-may26',
    title = 'VP Marketing (May 2026)'
WHERE slug = 'vp-marketing';

-- 3. Fresh fall VP Marketing row on the clean slug.
INSERT INTO public.positions
  (slug, title, description, phase, visibility, access_code, essay_questions,
   opens_at, closes_at, is_active)
VALUES
  ('vp-marketing',
   'VP Marketing (Video & Content)',
   'Own how TSI moves and sounds: reels, vlogs and mini-documentaries that make people stop scrolling and actually watch.',
   1, 'public', NULL,
   '[
     {"id": "vp-mkt-f26-1", "question": "Show don''t tell. Submit a video or reel that makes the case for why you''re the one for this role.", "max_words": 60}
   ]'::jsonb,
   '2026-09-05T04:00:00Z', '2026-09-12T04:10:00Z', false)
ON CONFLICT (slug) DO UPDATE SET
  title       = EXCLUDED.title,
  description = EXCLUDED.description,
  phase       = EXCLUDED.phase,
  visibility  = EXCLUDED.visibility,
  access_code = EXCLUDED.access_code,
  opens_at    = EXCLUDED.opens_at,
  closes_at   = EXCLUDED.closes_at,
  is_active   = false;

-- 4. PM: the 001-seeded Phase-2 row `pm-general` was reserved for a Sept
--    round and never activated. Take it over on the short slug.
UPDATE public.positions
SET slug = 'pm'
WHERE slug = 'pm-general' AND NOT EXISTS (SELECT 1 FROM public.positions WHERE slug = 'pm');

INSERT INTO public.positions
  (slug, title, description, phase, visibility, access_code, essay_questions,
   opens_at, closes_at, is_active)
VALUES
  ('pm',
   'Project Manager',
   'CEO of your own project. Lead a team of developers building real software for nonprofit clients, from kickoff to delivery at GENESIS.',
   1, 'public', NULL,
   '[
     {"id": "pm-f26-1", "question": "Tell us about a time you led a team through a hard project. What did you own, what did you delegate, and what would you do differently?", "max_words": 400},
     {"id": "pm-f26-2", "question": "Walk us through your most impressive technical project. What did you build, what was your role, and what did you learn?", "max_words": 400}
   ]'::jsonb,
   '2026-09-05T04:00:00Z', '2026-09-12T04:10:00Z', false)
ON CONFLICT (slug) DO UPDATE SET
  title           = EXCLUDED.title,
  description     = EXCLUDED.description,
  phase           = EXCLUDED.phase,
  visibility      = EXCLUDED.visibility,
  access_code     = EXCLUDED.access_code,
  essay_questions = EXCLUDED.essay_questions,
  opens_at        = EXCLUDED.opens_at,
  closes_at       = EXCLUDED.closes_at,
  is_active       = false;

COMMIT;
