-- Zone 1 mobs (specs/classes/design-sheet.md "Mobs, zone 1"): the Overgrown Outskirts' roster with the new pollen
-- sprite (a swarm), every zone-1 row's behaviour text (what its telegraph teaches), and the elder thorn crab as the
-- zone's mini-boss. Apply after 20261002052225_catalogue_seed. Idempotent.
-- Generated by web/scripts/gen-seeds.mjs from the TS catalogues (lib/seedMigrations.ts): each changed seed's
-- new block, then an upsert of its changed rows. Idempotent. Rows removed from the TS are not deleted here.

-- previous block: 20261001070514_guardian_balance_seed.sql
-- seed: combat
-- BEGIN GENERATED COMBAT SEED (web/scripts/gen-seeds.mjs)
INSERT INTO weapons (key, name, weapon_type, tier, scaling, max_durability, repair_per_point) VALUES
  ('sword-driftwood', 'Driftwood sword', 'sword', 1, ARRAY['might']::text[], 90, 1),
  ('sword-iron', 'Iron sword', 'sword', 2, ARRAY['might']::text[], 120, 2),
  ('shield-buckler', 'Buckler and blade', 'shield', 1, ARRAY['might','vitality']::text[], 90, 1),
  ('bow-willow', 'Willow bow', 'bow', 1, ARRAY['finesse']::text[], 90, 1),
  ('bow-yew', 'Yew longbow', 'bow', 2, ARRAY['finesse']::text[], 120, 2),
  ('revolver-brass', 'Brass revolver', 'revolver', 2, ARRAY['finesse']::text[], 120, 2),
  ('staff-oak', 'Oak staff', 'staff', 1, ARRAY['arcana']::text[], 90, 1),
  ('staff-rune', 'Rune staff', 'staff', 3, ARRAY['arcana']::text[], 150, 3),
  ('tome-spirits', 'Tome of small spirits', 'tome', 1, ARRAY['spirit']::text[], 90, 1),
  ('totem-cedar', 'Cedar totem', 'totem', 1, ARRAY['spirit']::text[], 90, 1),
  ('wraps-cloth', 'Cloth hand wraps', 'fists', 1, ARRAY['might','finesse']::text[], 90, 1),
  ('sword-guardian', 'Guardian''s edge', 'sword', 4, ARRAY['might']::text[], 180, 4),
  ('bow-sentinel', 'Sentinel bow', 'bow', 4, ARRAY['finesse']::text[], 180, 4),
  ('staff-sigil', 'Sigil staff', 'staff', 4, ARRAY['arcana']::text[], 180, 4),
  ('tome-warden', 'Warden''s grimoire', 'tome', 4, ARRAY['spirit']::text[], 180, 4),
  ('staff-heartstone', 'Heartstone staff', 'staff', 5, ARRAY['arcana','spirit']::text[], 210, 5)
ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, weapon_type = EXCLUDED.weapon_type, tier = EXCLUDED.tier, scaling = EXCLUDED.scaling, max_durability = EXCLUDED.max_durability, repair_per_point = EXCLUDED.repair_per_point;
INSERT INTO enemy_types (key, name, kind, zone, level, hp, damage, defense, armor, aggro_radius, attack_range, leash_radius, xp, behaviour) VALUES
  ('shadow-fox', 'Shadow fox', 'normal', 'outer', 5, 60, 8, 0, 0, 7, 1.5, 21, 30, 'Hunts in packs of three that circle to your sides. Each crouches, its mane and eyes flare, then it pounces down a line: step out of it.'),
  ('thorn-crab', 'Thorn crab', 'normal', 'outer', 5, 90, 10, 0.3, 0, 4, 1.2, 12, 35, 'Its front shell turns most hits aside and it turns slowly: circle to its flank or back. Raises both claws, then sweeps in front.'),
  ('mushroom-beast', 'Mushroom beast', 'normal', 'outer', 5, 110, 9, 0.1, 0, 6, 6.5, 18, 40, 'Its cap swells, then it lobs a spore ball onto the marked ring; the burst leaves a poison puddle for a few seconds.'),
  ('rune-wisp', 'Rune wisp', 'normal', 'outer', 5, 70, 9, 0, 0, 8, 7, 24, 40, 'Its runes spin up, then a bolt flies down the marked line. Close in and it shimmers and blinks away.'),
  ('pollen-sprite', 'Pollen sprite', 'normal', 'outer', 5, 14, 4, 0, 0, 7, 0.6, 21, 6, 'Drifts in clouds of 8 to 15 that circle you. One by one they flash, dart in and burst into pollen that slows you: swat them first.'),
  ('animated-book', 'Animated book', 'normal', 'inner', 10, 120, 13, 0.2, 0, 6, 2, 18, 65, 'Pages flutter open, then it snaps shut on a short charge.'),
  ('stone-golem', 'Stone golem', 'elite', 'inner', 12, 420, 22, 0.45, 2, 6, 2.5, 18, 220, 'Raises both fists, core glows, then slams the ground around it.'),
  ('elder-thorn-crab', 'Elder thorn crab', 'elite', 'outer', 7, 300, 16, 0.4, 0, 5, 1.8, 15, 160, 'Mini-boss. Shell closed: armoured, slow claw sweeps, hit it from behind. Cracked at 60%: faster, and it charges down a marked lane. Enraged at 25%: claw slams with shockwaves to dodge through.'),
  ('guardian-statue', 'Guardian statue', 'boss', 'boss', 15, 1700, 28, 0.35, 7, 9, 3, 11, 1200, 'Overhead slam on a ring marker, a sigil beam sweep with a stagger after it, two rune wisps below half health, enraged at a fifth.')
ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, kind = EXCLUDED.kind, zone = EXCLUDED.zone, level = EXCLUDED.level, hp = EXCLUDED.hp, damage = EXCLUDED.damage, defense = EXCLUDED.defense, armor = EXCLUDED.armor, aggro_radius = EXCLUDED.aggro_radius, attack_range = EXCLUDED.attack_range, leash_radius = EXCLUDED.leash_radius, xp = EXCLUDED.xp, behaviour = EXCLUDED.behaviour;
INSERT INTO missions (key, title, template, zone, difficulty, params, rewards, cooldown_hours) VALUES
  ('hunt-foxes', 'Fox trouble', 'hunt', 'outer', 1, '{"enemy":"shadow-fox","count":6}'::jsonb, '{"xp":300,"coins":60,"materials":{"wood_branch":3}}'::jsonb, 20),
  ('hunt-crabs', 'Crab season', 'hunt', 'outer', 2, '{"enemy":"thorn-crab","count":5}'::jsonb, '{"xp":320,"coins":60,"materials":{"rock_stone":3}}'::jsonb, 20),
  ('hunt-wisps', 'Put out the wisps', 'hunt', 'outer', 2, '{"enemy":"rune-wisp","count":4}'::jsonb, '{"xp":360,"coins":70,"materials":{"rock_crystal":1}}'::jsonb, 20),
  ('hunt-golem', 'Break the golem', 'hunt', 'inner', 4, '{"enemy":"stone-golem","count":1}'::jsonb, '{"xp":700,"coins":150,"materials":{"rock_iron_nugget":3}}'::jsonb, 20),
  ('fetch-lantern', 'The lost lantern', 'fetch', 'outer', 1, '{"item":"old-lantern","chamber":"fox-den"}'::jsonb, '{"xp":350,"coins":70,"materials":{"rock_clay":2}}'::jsonb, 20),
  ('fetch-tome', 'An overdue book', 'fetch', 'inner', 3, '{"item":"sealed-tome","chamber":"library"}'::jsonb, '{"xp":650,"coins":120,"materials":{"rock_gold_nugget":1}}'::jsonb, 20),
  ('survive-circle', 'Hold the rune circle', 'survive', 'outer', 2, '{"waves":3}'::jsonb, '{"xp":400,"coins":80,"materials":{"rock_iron_nugget":2}}'::jsonb, 20),
  ('survive-sanctum', 'Sanctum watch', 'survive', 'inner', 4, '{"waves":4}'::jsonb, '{"xp":800,"coins":160,"materials":{"rock_crystal":2}}'::jsonb, 20),
  ('escort-botanist', 'The botanist''s walk', 'escort', 'outer', 2, '{"resident":"botanist","checkpoints":3}'::jsonb, '{"xp":380,"coins":75,"materials":{"wood_branch":4}}'::jsonb, 20),
  ('escort-scholar', 'Scholar to the shrine', 'escort', 'inner', 3, '{"resident":"scholar","checkpoints":4}'::jsonb, '{"xp":750,"coins":150,"materials":{"rock_gold_nugget":1,"rock_crystal":1}}'::jsonb, 20)
ON CONFLICT (key) DO UPDATE SET title = EXCLUDED.title, template = EXCLUDED.template, zone = EXCLUDED.zone, difficulty = EXCLUDED.difficulty, params = EXCLUDED.params, rewards = EXCLUDED.rewards, cooldown_hours = EXCLUDED.cooldown_hours;
-- END GENERATED COMBAT SEED
