-- Generated by web/scripts/gen-seeds.mjs from the TS catalogues (lib/seedMigrations.ts): each changed seed's
-- new block, then an upsert of its changed rows. Idempotent. Rows removed from the TS are not deleted here.

-- previous block: 20260926150500_study.sql
-- seed: study-tables
-- BEGIN GENERATED STUDY TABLES (web/scripts/gen-seeds.mjs)
INSERT INTO study_tables (id, slug, label, location, anchor, kind, seats, position) VALUES
  ('00000000-0000-4000-8000-000000005101', 'cafe-window-1', 'Window bar 1', 'cafe', 'study:cafe-window-1', 'window', 2, 1),
  ('00000000-0000-4000-8000-000000005102', 'cafe-window-2', 'Window bar 2', 'cafe', 'study:cafe-window-2', 'window', 2, 2),
  ('00000000-0000-4000-8000-000000005103', 'cafe-two-1', 'Table for two', 'cafe', 'study:cafe-two-1', 'two', 2, 3),
  ('00000000-0000-4000-8000-000000005104', 'cafe-two-2', 'Corner table for two', 'cafe', 'study:cafe-two-2', 'two', 2, 4),
  ('00000000-0000-4000-8000-000000005105', 'cafe-four-1', 'Table for four', 'cafe', 'study:cafe-four-1', 'four', 4, 5),
  ('00000000-0000-4000-8000-000000005106', 'cafe-four-2', 'Communal table', 'cafe', 'study:cafe-four-2', 'four', 4, 6),
  ('00000000-0000-4000-8000-000000005107', 'cafe-couch', 'Booth', 'cafe', 'study:cafe-couch', 'couch', 4, 7),
  ('00000000-0000-4000-8000-000000005108', 'plaza-picnic', 'Plaza picnic table', 'outdoor-plaza', 'study:plaza-picnic', 'outdoor', 4, 8),
  ('00000000-0000-4000-8000-000000005109', 'pier-bench', 'Pier table', 'outdoor-pier', 'study:pier-bench', 'outdoor', 2, 9)
ON CONFLICT (id) DO NOTHING;
-- END GENERATED STUDY TABLES
-- The rows this change adds or edits, so they land where the insert above does nothing.
INSERT INTO study_tables (id, slug, label, location, anchor, kind, seats, position) VALUES
  ('00000000-0000-4000-8000-000000005101', 'cafe-window-1', 'Window bar 1', 'cafe', 'study:cafe-window-1', 'window', 2, 1),
  ('00000000-0000-4000-8000-000000005102', 'cafe-window-2', 'Window bar 2', 'cafe', 'study:cafe-window-2', 'window', 2, 2),
  ('00000000-0000-4000-8000-000000005105', 'cafe-four-1', 'Table for four', 'cafe', 'study:cafe-four-1', 'four', 4, 5),
  ('00000000-0000-4000-8000-000000005106', 'cafe-four-2', 'Communal table', 'cafe', 'study:cafe-four-2', 'four', 4, 6),
  ('00000000-0000-4000-8000-000000005107', 'cafe-couch', 'Booth', 'cafe', 'study:cafe-couch', 'couch', 4, 7)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, label = EXCLUDED.label, location = EXCLUDED.location, anchor = EXCLUDED.anchor, kind = EXCLUDED.kind, seats = EXCLUDED.seats, position = EXCLUDED.position;
