-- ─── Classes v2, the Warden wave: signature weapons, shop cosmetics, the Summoner's tamings ─
--
-- DRAFT 2026-10-03. NOT APPLIED. Apply after 20261003015109_classes_v2_arcane_seed (and every migration before it on main).
-- Spec: specs/classes/design-sheet.md "Summoner (LOCKED)", "Shaman (LOCKED)", "Druid (LOCKED)", "Priest (LOCKED)",
-- §1.5 signature weapons, §1.10 shop cosmetics. Everything here waits behind economy_settings.classes_v2 (off).
-- Test: web/supabase/tests/classes_v2_warden_smoke.sql.

-- ─── Signature weapons (§1.5): seal gloves, the carved totem staff, the living staff, the sunstone staff ─
-- Five tiers each, Spirit-scaled (the living staff also Vitality). Generated by signatureSeedSql (web/lib/combat/seed.ts)
-- from WARDEN_WEAPONS (web/lib/combat/wardenData.ts); a test holds this block to it.
INSERT INTO weapons (key, name, weapon_type, tier, scaling, max_durability, repair_per_point, subclass) VALUES
  ('seal-gloves-1', 'Ink seal gloves', 'seal-gloves', 1, ARRAY['spirit']::text[], 90, 1, 'summoner'),
  ('seal-gloves-2', 'Iron-bound seal gloves', 'seal-gloves', 2, ARRAY['spirit']::text[], 120, 2, 'summoner'),
  ('seal-gloves-3', 'Rune-carved seal gloves', 'seal-gloves', 3, ARRAY['spirit']::text[], 150, 3, 'summoner'),
  ('seal-gloves-4', 'Gilded seal gloves', 'seal-gloves', 4, ARRAY['spirit']::text[], 180, 4, 'summoner'),
  ('seal-gloves-5', 'Shadow sovereign gloves', 'seal-gloves', 5, ARRAY['spirit']::text[], 210, 5, 'summoner'),
  ('totem-staff-1', 'Carved totem staff', 'totem-staff', 1, ARRAY['spirit']::text[], 90, 1, 'shaman'),
  ('totem-staff-2', 'Iron-bound totem staff', 'totem-staff', 2, ARRAY['spirit']::text[], 120, 2, 'shaman'),
  ('totem-staff-3', 'Rune-carved totem staff', 'totem-staff', 3, ARRAY['spirit']::text[], 150, 3, 'shaman'),
  ('totem-staff-4', 'Gilded totem staff', 'totem-staff', 4, ARRAY['spirit']::text[], 180, 4, 'shaman'),
  ('totem-staff-5', 'Thunder spirit staff', 'totem-staff', 5, ARRAY['spirit']::text[], 210, 5, 'shaman'),
  ('living-staff-1', 'Living staff', 'living-staff', 1, ARRAY['spirit','vitality']::text[], 90, 1, 'druid'),
  ('living-staff-2', 'Iron-bound living staff', 'living-staff', 2, ARRAY['spirit','vitality']::text[], 120, 2, 'druid'),
  ('living-staff-3', 'Rune-carved living staff', 'living-staff', 3, ARRAY['spirit','vitality']::text[], 150, 3, 'druid'),
  ('living-staff-4', 'Gilded living staff', 'living-staff', 4, ARRAY['spirit','vitality']::text[], 180, 4, 'druid'),
  ('living-staff-5', 'Elderbloom staff', 'living-staff', 5, ARRAY['spirit','vitality']::text[], 210, 5, 'druid'),
  ('sunstone-staff-1', 'Sunstone staff', 'sunstone-staff', 1, ARRAY['spirit']::text[], 90, 1, 'priest'),
  ('sunstone-staff-2', 'Iron-bound sunstone staff', 'sunstone-staff', 2, ARRAY['spirit']::text[], 120, 2, 'priest'),
  ('sunstone-staff-3', 'Rune-carved sunstone staff', 'sunstone-staff', 3, ARRAY['spirit']::text[], 150, 3, 'priest'),
  ('sunstone-staff-4', 'Gilded sunstone staff', 'sunstone-staff', 4, ARRAY['spirit']::text[], 180, 4, 'priest'),
  ('sunstone-staff-5', 'Dawnfire staff', 'sunstone-staff', 5, ARRAY['spirit']::text[], 210, 5, 'priest')
ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, weapon_type = EXCLUDED.weapon_type, tier = EXCLUDED.tier, scaling = EXCLUDED.scaling, max_durability = EXCLUDED.max_durability, repair_per_point = EXCLUDED.repair_per_point, subclass = EXCLUDED.subclass;

-- ─── Shop cosmetics (§1.10): weapon skins and aura colours ─────────────────
-- Mostly coins; two Gem items (an animated skin, a two-tone aura). Never a rate.
INSERT INTO shop_items (slug, display_name, category, description, price_coins, tc_price, cosmetic, sprite_url, position, active) VALUES
  ('skin-seal-gloves-moonink', 'Moon-ink seal gloves', 'weapon_skin', 'A Summoner skin: ink-blue gloves, the seals in moonlight. Every tier.', 800, NULL, '{"subclass":"summoner","skin":"moonink"}', '/assets/game/classes/summoner.svg', 920, TRUE),
  ('skin-totem-staff-birch', 'Birch spirit staff', 'weapon_skin', 'A Shaman skin: pale birch, the faces carved in charcoal. Every tier.', 800, NULL, '{"subclass":"shaman","skin":"birch"}', '/assets/game/classes/shaman.svg', 921, TRUE),
  ('skin-totem-staff-aurora', 'Aurora storm staff', 'weapon_skin', 'A Shaman skin whose carvings shimmer like an aurora. Every tier.', NULL, 200, '{"subclass":"shaman","skin":"aurora","animated":true}', '/assets/game/classes/shaman.svg', 922, TRUE),
  ('skin-living-staff-cherry', 'Cherry blossom staff', 'weapon_skin', 'A Druid skin: dark cherry wood in blossom. Every tier.', 800, NULL, '{"subclass":"druid","skin":"cherry"}', '/assets/game/classes/druid.svg', 923, TRUE),
  ('skin-sunstone-staff-dawn', 'Dawnglass staff', 'weapon_skin', 'A Priest skin: pearl wood and a rose sunstone. Every tier.', 800, NULL, '{"subclass":"priest","skin":"dawn"}', '/assets/game/classes/priest.svg', 924, TRUE),
  ('aura-warden-moss', 'Moss lantern aura', 'aura', 'Aura colours: moss and lantern light.', 300, NULL, '{"ramp":["#f4ffe6","#9bd36a","#23401a"]}', '/assets/game/classes/aura-warden-moss.svg', 925, TRUE),
  ('aura-warden-tide', 'Tidepool aura', 'aura', 'Aura colours: tidepool teal.', 300, NULL, '{"ramp":["#effcff","#5fc9d6","#0f3540"]}', '/assets/game/classes/aura-warden-tide.svg', 926, TRUE),
  ('aura-warden-ember', 'Hearth ember aura', 'aura', 'Aura colours: hearth embers.', 300, NULL, '{"ramp":["#fff4e0","#f0a050","#40200c"]}', '/assets/game/classes/aura-warden-ember.svg', 927, TRUE),
  ('aura-warden-sunrise', 'Sunrise shimmer aura', 'aura', 'Two-tone aura colours that shimmer at dawn.', NULL, 150, '{"ramp":["#fffbe6","#f2b75c","#4a2a10"],"shimmer":"#9fe3ff"}', '/assets/game/classes/aura-warden-sunrise.svg', 928, TRUE)
ON CONFLICT (slug) DO NOTHING;

-- ─── The Summoner's tamings (design sheet: each beast is tamed before use) ─────
-- Wolves are known from the start (never stored). The owl, the toad, the serpent and the rabbits are tamed in that order
-- at the ritual circle in the ruins, by beating each one's untamed form alone; the client reports the fall (kills are
-- client-reported too, ruling 3) and this records it once per key. Members read their own; only the function writes.
CREATE TABLE IF NOT EXISTS member_tamed_beasts (
  member_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  beast TEXT NOT NULL CHECK (beast IN ('owl', 'toad', 'serpent', 'rabbits')),
  idempotency_key TEXT NOT NULL,
  tamed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (member_id, beast),
  UNIQUE (member_id, idempotency_key)
);
ALTER TABLE member_tamed_beasts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Tamed beasts readable by owner" ON member_tamed_beasts;
CREATE POLICY "Tamed beasts readable by owner" ON member_tamed_beasts FOR SELECT USING (member_id = (select auth.uid()));

-- The next beast in turn, for a Summoner, with the flag on. A replayed key (or a beast already tamed) answers with the
-- list as it stands. Returns every tamed beast in taming order.
CREATE OR REPLACE FUNCTION public.combat_tame_beast(p_member_id UUID, p_beast TEXT, p_key TEXT)
RETURNS TABLE (tamed TEXT[], replayed BOOLEAN) LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
#variable_conflict use_column
DECLARE p member_progression%ROWTYPE; v_order CONSTANT TEXT[] := ARRAY['owl', 'toad', 'serpent', 'rabbits']; v_next TEXT;
BEGIN
  PERFORM public.combat_ensure(p_member_id);
  SELECT * INTO p FROM member_progression WHERE member_id = p_member_id FOR UPDATE;  -- serialise tamings
  IF EXISTS (SELECT 1 FROM member_tamed_beasts t WHERE t.member_id = p_member_id AND (t.idempotency_key = p_key OR t.beast = p_beast)) THEN
    RETURN QUERY SELECT ARRAY(SELECT t.beast FROM member_tamed_beasts t WHERE t.member_id = p_member_id ORDER BY array_position(v_order, t.beast)), TRUE;
    RETURN;
  END IF;
  IF NOT public.classes_v2_on() THEN RAISE EXCEPTION 'unavailable'; END IF;
  IF p.subclass IS DISTINCT FROM 'summoner' THEN RAISE EXCEPTION 'bad_beast'; END IF;
  SELECT o.b INTO v_next FROM unnest(v_order) WITH ORDINALITY AS o(b, i)
   WHERE NOT EXISTS (SELECT 1 FROM member_tamed_beasts t WHERE t.member_id = p_member_id AND t.beast = o.b) ORDER BY o.i LIMIT 1;
  IF v_next IS DISTINCT FROM p_beast THEN RAISE EXCEPTION 'bad_beast'; END IF;
  INSERT INTO member_tamed_beasts (member_id, beast, idempotency_key) VALUES (p_member_id, p_beast, p_key);
  RETURN QUERY SELECT ARRAY(SELECT t.beast FROM member_tamed_beasts t WHERE t.member_id = p_member_id ORDER BY array_position(v_order, t.beast)), FALSE;
END;
$$;
REVOKE ALL ON FUNCTION public.combat_tame_beast(UUID, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.combat_tame_beast(UUID, TEXT, TEXT) TO service_role;
