// Generated by art/fx/build_pack.py: do not edit (change the COMBAT_SPRITES list there and rebuild).
/** The combat pack (specs/classes/design-sheet.md §1.7): heat in RGB, coverage in A; the shader maps heat through the effect's ramp. */
export const COMBAT_PACK_URL = "/assets/fx/combat-pack.webp";
export const COMBAT_PACK_COLS = 8;
export const COMBAT_PACK_ROWS = 31;
export const COMBAT_PACK = {
  impactStar: { row: 0, frames: 8 } /* spiky impact star: pops open, hollows out */,
  slash: { row: 1, frames: 8 } /* crescent slash arc: sweeps on, thins away */,
  sparkBurst: { row: 2, frames: 8 } /* spark streaks flying out of a hit */,
  shockRing: { row: 3, frames: 8 } /* shock ring: bursts out, breaks up */,
  smoke: { row: 4, frames: 8 } /* dark cel smoke puff (two bands) */,
  swirl: { row: 5, frames: 8 } /* energy swirl gathering into a core */,
  halo: { row: 6, frames: 8 } /* glow halo: hard core, soft breathing glow */,
  speedLine: { row: 7, frames: 8 } /* tapered speed line along +u */,
  debris: { row: 8, frames: 8 } /* rock chunks tumbling */,
  rune: { row: 9, frames: 8 } /* rune circle: draws in, flares, dissolves */,
  mote: { row: 10, frames: 8 } /* aura light mote (6 px core) */,
  crack: { row: 11, frames: 8 } /* ground crack decal (lies on the ground) */,
  beam: { row: 12, frames: 8 } /* beam segment along +u (tiles along u) */,
  ink: { row: 13, frames: 8 } /* black ink splash and flicks */,
  flare: { row: 14, frames: 8 } /* four-point flare star */,
  flame: { row: 15, frames: 8 } /* fire tongue licking up, tip tears off (loops) */,
  droplet: { row: 16, frames: 8 } /* water spray: drops fly out and fall */,
  wave: { row: 17, frames: 8 } /* wave crest side-on: curls forward, crashes */,
  petal: { row: 18, frames: 8 } /* blossom opens, its petals fall tumbling */,
  cloud: { row: 19, frames: 8 } /* dark storm-cloud puff, a few rim lights */,
  card: { row: 20, frames: 8 } /* playing card flipping as it spins (loops) */,
  shard: { row: 21, frames: 8 } /* glass shard tumbling, glint edge */,
  bone: { row: 22, frames: 8 } /* bone fragment tumbling */,
  skull: { row: 23, frames: 8 } /* skull glyph aura mote: pops in, fades */,
  beast: { row: 24, frames: 8 } /* fox, crab, wisp, pollen, golem glyphs (loops) */,
  muzzle: { row: 25, frames: 8 } /* muzzle blast along +u */,
  chain: { row: 26, frames: 8 } /* chain links along +u (tiles) */,
  mushroom: { row: 27, frames: 8 } /* mushroom cloud: fireball, cap, skirt */,
  inkSlash: { row: 28, frames: 8 } /* ink brush slash with a mid rim */,
  lotusPetal: { row: 29, frames: 8 } /* lotus petal: tumbles, fades from the tip */,
  aegisShard: { row: 30, frames: 8 } /* shield shard: faceted plate, glint sweep */,
} as const;
export type CombatSprite = keyof typeof COMBAT_PACK;
