// Generated by art/fx/build_mob_pack.py: do not edit (change the SPRITES list there and rebuild).
/** Zone 1's attack effects (design sheet "Mobs, zone 1"): one row of 8 frames per sprite, 128 px cells, beside the movement pack. */
export const MOB_PACK_URL = "/assets/fx/mob-pack.webp";
export const MOB_PACK_COLS = 8;
export const MOB_PACK_ROWS = 10;
export const MOB_PACK = {
  spores: { row: 0, frames: 8 } /* spore burst (the mushroom) */,
  pollen: { row: 1, frames: 8 } /* pollen burst (a sprite) */,
  mote: { row: 2, frames: 8 } /* bright mote (pollen, spores, glints) */,
  runeSpark: { row: 3, frames: 8 } /* rune glyph spark (bolts, blinks) */,
  runeCircle: { row: 4, frames: 8 } /* blink circle (lies on the ground) */,
  slash: { row: 5, frames: 8 } /* claw slash, three crescents */,
  shockRing: { row: 6, frames: 8 } /* shockwave dust ring (lies on the ground) */,
  puddle: { row: 7, frames: 8 } /* poison puddle (lies on the ground, loops) */,
  impact: { row: 8, frames: 8 } /* impact star (pounce, charge) */,
  shard: { row: 9, frames: 8 } /* shell chips */,
} as const;
export type MobSprite = keyof typeof MOB_PACK;
