// Generated by art/fx/build_pack.py: do not edit (change the SPRITES list there and rebuild).
/** Our particle pack (specs/movement-feel.md deliverable 1): one row of 8 frames per sprite, 128 px cells. */
export const PACK_URL = "/assets/fx/move-pack.webp";
export const PACK_COLS = 8;
export const PACK_ROWS = 18;
export const PACK = {
  dust: { row: 0, frames: 8 } /* dust puff */,
  dustLow: { row: 1, frames: 8 } /* low dust burst (hugs the ground) */,
  sand: { row: 2, frames: 8 } /* sand kick */,
  grass: { row: 3, frames: 8 } /* grass flecks */,
  droplets: { row: 4, frames: 8 } /* water droplets */,
  ripple: { row: 5, frames: 8 } /* water ripple (lies on the water) */,
  snow: { row: 6, frames: 8 } /* snow puff */,
  leaf: { row: 7, frames: 8 } /* leaf bit (tumbling) */,
  streak: { row: 8, frames: 8 } /* soft tapered speed streak */,
  swirl: { row: 9, frames: 8 } /* wind swirl */,
  scuff: { row: 10, frames: 8 } /* skid scuff (lies on the ground) */,
  sparkle: { row: 11, frames: 8 } /* tiny sparkle */,
  marker: { row: 12, frames: 8 } /* ground marker (target) */,
  footprint: { row: 13, frames: 8 } /* footprint in snow (lies on the ground) */,
  sandPrint: { row: 14, frames: 8 } /* shoe print in sand (lies on the ground) */,
  splash: { row: 15, frames: 8 } /* splash crown (stands on the water) */,
  foam: { row: 16, frames: 8 } /* wake foam (lies on the water) */,
  spray: { row: 17, frames: 8 } /* bow spray (thrown drops and mist) */,
} as const;
export type SpriteName = keyof typeof PACK;
