import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { ARCANE_KITS } from "@/lib/combat/arcaneKits";
import { balanceRowV2, bandV2, bossMinutes, bossMinutesV2, runV2, V2_TARGETS, type BalanceRowV2 } from "./balance";

/**
 * The Arcane wave's harness rows (design sheet §3, the v2 bot): mastery 1 on the normal and the sanctum runs, mastery 20
 * on the normal run, the scripted guardian fight. The band is held among the four, and against today's 16-kit median
 * (specs/evidence/combat-b/balance.md: 27.5 normal DPS) so the next waves land on the same scale.
 */
const SEEDS = 12, TODAY = 27.5;
const keys = ARCANE_KITS.map(k => k.key);
const normal = keys.map(k => balanceRowV2(k, "survive-circle", 1, SEEDS)), hard = keys.map(k => balanceRowV2(k, "survive-sanctum", 1, SEEDS));
const top = keys.map(k => balanceRowV2(k, "survive-circle", 20, SEEDS));
const med = (v: number[]) => { const s = [...v].sort((a, b) => a - b); return (s[(s.length - 1) >> 1] + s[s.length >> 1]) / 2; };

describe("the Arcane kits in the band (§3)", () => {
  const band = bandV2(normal, hard);
  it("clear every normal and sanctum run", () => {
    for (const r of [...normal, ...hard]) { expect(r.clearRate, r.subclass).toBe(1); expect(r.deaths, r.subclass).toBe(0); }
  });
  it("normal-run DPS within ±25% of the median, and of today's median", () => {
    expect(band.dpsLow).toBeGreaterThanOrEqual(V2_TARGETS.dpsBand[0]); expect(band.dpsHigh).toBeLessThanOrEqual(V2_TARGETS.dpsBand[1]);
    for (const r of normal) { expect(r.dps / TODAY, r.subclass).toBeGreaterThan(0.75); expect(r.dps / TODAY, r.subclass).toBeLessThan(1.25); }
  });
  it("sanctum damage taken within a 3× spread; no clear under 0.7× the median", () => {
    expect(band.spread).toBeLessThanOrEqual(V2_TARGETS.takenSpread);
    expect(band.clearNormal).toBeGreaterThanOrEqual(V2_TARGETS.clearFloor); expect(band.clearHard).toBeGreaterThanOrEqual(V2_TARGETS.clearFloor);
  });
  it("the meter fills in about a minute on the sanctum run (45–90 s)", () => {
    for (const r of hard) { expect(r.ultFill, r.subclass).toBeGreaterThan(45); expect(r.ultFill, r.subclass).toBeLessThan(90); }
  });
  // §3 asks 1.2×; the locked clone counts (4 at 20, 18 s) and the 0.75 s form cooldown put it at about 1.3 (arcane-questions.md).
  it("mastery 20 adds options more than power: the median about 1.3× mastery 1's at most", () => {
    expect(med(top.map(r => r.dps)) / med(normal.map(r => r.dps))).toBeLessThan(1.35);
  });
  it("writes specs/evidence/classes/K-arcane-balance.md when asked (WRITE_BALANCE=1)", () => {
    if (!process.env.WRITE_BALANCE) return;
    const boss = keys.map(k => { const runs = Array.from({ length: 6 }, (_, i) => runV2(k, "boss", i + 1, 1, 600)); return { median: bossMinutesV2(k, 1, 6), deaths: runs.filter(r => r.died).length, cleared: runs.filter(r => r.cleared).map(r => r.seconds / 60) }; });
    const f = (r: BalanceRowV2, ref: number) => `| ${r.subclass} | ${r.role} | ${r.mastery} | ${r.weapon} | ${Math.round(r.clearRate * 100)}% | ${Math.round(r.medianClear)} s | ${r.dps.toFixed(1)} | ${(r.dps / ref).toFixed(2)}× | ${Math.round(r.takenPerMin)} | ${Math.round(r.minHp * 100)}% | ${Number.isFinite(r.ultFill) ? `${Math.round(r.ultFill)} s` : "–"} | ${Math.round(r.ultShare * 100)}% |`;
    const head = ["| Kit | Role | Mastery | Weapon | Cleared | Median clear | DPS | vs median | Taken / min | Lowest HP | Ult fill | Ult share |", "|---|---|---|---|---|---|---|---|---|---|---|---|"];
    const m1 = med(normal.map(r => r.dps)), mh = med(hard.map(r => r.dps));
    writeFileSync(join(__dirname, "../../../../specs/evidence/classes/K-arcane-balance.md"), [
      "# Classes v2, the Arcane wave: harness rows", "",
      `Generated by \`web/lib/game/combat/arcaneBalance.test.ts\` (\`WRITE_BALANCE=1\`). The v2 bot (design sheet §3, \`runV2\`): level 10 with the Arcane preset, the tier-1 signature weapon, keys through the input layer, movement riders on 30% of casts, 60% of telegraphs dodged and a third of the rest answered with a timed skill pressed at a human moment, the ult at a full meter on two or more enemies or the boss. ${SEEDS} seeds a row. "vs median" is against the four's median; today's 16 kits (combat-b/balance.md) sit at a 27.5 normal-DPS median.`, "",
      "## Hold the rune circle (normal), mastery 1", "", ...head, ...normal.map(r => f(r, m1)), "",
      "## Sanctum watch (harder), mastery 1", "", ...head, ...hard.map(r => f(r, mh)), "",
      "## Hold the rune circle, mastery 20 (every key, every rank, the stat direction at its top)", "", ...head, ...top.map(r => f(r, med(top.map(x => x.dps)))), "",
      `Mastery 20 over mastery 1 (medians): ×${(med(top.map(r => r.dps)) / m1).toFixed(2)}.`, "",
      "## The guardian", "",
      "| Kit | Scripted fight (median of 6, 10 = never fell) | Deaths in 6 | Its kills (min) | Formula (signature weapon, content pass measure) |", "|---|---|---|---|---|",
      ...keys.map((k, i) => `| ${normal[i].subclass} | ${boss[i].median.toFixed(1)} min | ${boss[i].deaths} | ${boss[i].cleared.map(x => x.toFixed(1)).join(", ") || "–"} | ${bossMinutes(`${ARCANE_KITS[i].signature.type}-1`).toFixed(1)} min |`), "",
      "## The band", "",
      `- Normal DPS ${band.dpsLow.toFixed(2)}–${band.dpsHigh.toFixed(2)}× the four's median (target 0.75–1.25); against today's median ${Math.min(...normal.map(r => r.dps / TODAY)).toFixed(2)}–${Math.max(...normal.map(r => r.dps / TODAY)).toFixed(2)}×.`,
      `- Roles against today's median: ${normal.map(r => `${r.subclass} (${r.role}) ${(r.dps / TODAY).toFixed(2)}×`).join(", ")}.`,
      `- Sanctum damage taken spread ${band.spread.toFixed(2)}× (target ≤ 3); clears ${band.clearNormal.toFixed(2)}× and ${band.clearHard.toFixed(2)}× the median at the fastest (target ≥ 0.7).`,
      `- Ult fill on the sanctum ${hard.map(r => `${r.subclass} ${Math.round(r.ultFill)} s`).join(", ")} (target 60–90); share ${hard.map(r => `${Math.round(r.ultShare * 100)}%`).join(", ")} (target 8–15%).`, "",
    ].join("\n"));
  });
}, 1200000);
