import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { balanceTable, familyAverages, type BalanceRow } from "./balance";

const pct = (n: number) => `${Math.round(n * 100)}%`;
const table = (rows: BalanceRow[]) => [
  "| Subclass | Family | Starter weapon | Cleared | Median clear | DPS | Damage taken / min | Lowest HP (avg) | Deaths |",
  "|---|---|---|---|---|---|---|---|---|",
  ...rows.map(r => `| ${r.subclass} | ${r.family} | ${r.weapon} | ${pct(r.clearRate)} | ${Number.isNaN(r.medianClear) ? "–" : `${Math.round(r.medianClear)} s`} | ${r.dps.toFixed(1)} | ${Math.round(r.takenPerMin)} | ${pct(r.minHp)} | ${r.deaths} |`),
].join("\n");
const families = (rows: BalanceRow[]) => ["| Family | Cleared | Median clear (avg) | DPS | Damage taken / min | Lowest HP (avg) |", "|---|---|---|---|---|---|",
  ...familyAverages(rows).map(f => `| ${f.family} | ${pct(f.clearRate)} | ${Math.round(f.medianClear)} s | ${f.dps.toFixed(1)} | ${Math.round(f.takenPerMin)} | ${pct(f.minHp)} |`)].join("\n");

describe("balance pass (Part B 3, G2): scripted solo survive runs, 20 seeds per subclass", () => {
  const normal = balanceTable("survive-circle");
  const hard = balanceTable("survive-sanctum");
  it("every subclass clears a normal mission solo (Hold the rune circle)", () => {
    for (const r of normal) expect(r.clearRate, r.subclass).toBeGreaterThanOrEqual(0.9);
  });
  it("Warden is slightly favoured: the most reliable family on the harder run (clears, lowest health), yet not the fastest by a mile", () => {
    const fam = familyAverages(hard), warden = fam.find(f => f.family === "Warden")!;
    for (const f of fam.filter(x => x.family !== "Warden")) {
      expect(warden.clearRate, f.family).toBeGreaterThanOrEqual(f.clearRate);
      expect(warden.minHp, f.family).toBeGreaterThan(f.minHp);
    }
    const fastest = Math.min(...fam.map(f => f.medianClear));
    expect(warden.medianClear).toBeLessThan(fastest * 1.6); // strong solo fighters, not just survivors
    expect(warden.medianClear).toBeGreaterThan(fastest * 0.7); // …and not a steamroller
  });
  it("writes specs/evidence/combat-b/balance.md when asked (WRITE_BALANCE=1)", () => {
    if (!process.env.WRITE_BALANCE) return;
    writeFileSync(join(__dirname, "../../../../specs/evidence/combat-b/balance.md"), [
      "# Combat B balance pass: scripted solo runs (G2)",
      "",
      "Generated by `web/lib/game/combat/balance.test.ts` (`WRITE_BALANCE=1 npx vitest run lib/game/combat/balance.test.ts`). Every subclass at level 10 with its family stat preset, the starter weapon (of the five the gate grants) that scales with its family's stat, the kit's suggestion where one does, and the default loadout (signature, its two own abilities, the family's second). The bot closes to its weapon's range and holds (no kiting), dodges 60% of the telegraphs aimed at it, uses an ability when it helps, and draws runes at about 80% (one in ten fizzles, one in ten empowered). Same encounter tick and ability system as the ruins (`encounter.ts`, `abilities.ts`), open ground, 20 seeds per row, 240 s limit.",
      "",
      "## Normal mission: Hold the rune circle (outer wild, 3 waves, level 5 enemies)",
      "",
      table(normal),
      "",
      families(normal),
      "",
      "## Harder reference: Sanctum watch (inner temple, 4 waves of books and golems, levels 10–12)",
      "",
      table(hard),
      "",
      families(hard),
      "",
      "DPS is damage dealt (weapon, abilities and summons) over the run's length; damage taken is after guard, blocks and shields. The numbers are the starting balance; tune after the member playtest.",
      "",
    ].join("\n"));
  });
});
