import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { balanceTable, bossMinutes, elderTable, familyAverages, type BalanceRow } from "./balance";

const pct = (n: number) => `${Math.round(n * 100)}%`;
const table = (rows: BalanceRow[]) => [
  "| Subclass | Family | Starter weapon | Cleared | Median clear | DPS | Damage taken / min | Lowest HP (avg) | Deaths |",
  "|---|---|---|---|---|---|---|---|---|",
  ...rows.map(r => `| ${r.subclass} | ${r.family} | ${r.weapon} | ${pct(r.clearRate)} | ${Number.isNaN(r.medianClear) ? "–" : `${Math.round(r.medianClear)} s`} | ${r.dps.toFixed(1)} | ${Math.round(r.takenPerMin)} | ${pct(r.minHp)} | ${r.deaths} |`),
].join("\n");
const families = (rows: BalanceRow[]) => ["| Family | Cleared | Median clear (avg) | DPS | Damage taken / min | Lowest HP (avg) |", "|---|---|---|---|---|---|",
  ...familyAverages(rows).map(f => `| ${f.family} | ${pct(f.clearRate)} | ${Math.round(f.medianClear)} s | ${f.dps.toFixed(1)} | ${Math.round(f.takenPerMin)} | ${pct(f.minHp)} |`)].join("\n");

const median = (v: number[]) => { const s = [...v].sort((a, b) => a - b); return (s[(s.length - 1) >> 1] + s[s.length >> 1]) / 2; };
/** The band (combat polish 11): normal-mission DPS within ±25% of the median, sanctum damage taken within a 3× spread, no clear under 0.7× its mission's median. */
function band(normal: BalanceRow[], hard: BalanceRow[]) {
  const dps = median(normal.map(r => r.dps)), taken = hard.map(r => r.takenPerMin);
  const clear = (rows: BalanceRow[]) => Math.min(...rows.map(r => r.medianClear)) / median(rows.map(r => r.medianClear));
  return { dpsLow: Math.min(...normal.map(r => r.dps)) / dps, dpsHigh: Math.max(...normal.map(r => r.dps)) / dps, spread: Math.max(...taken) / Math.min(...taken), clearNormal: clear(normal), clearHard: clear(hard) };
}
const WEAPONS_NAME: Record<string, string> = { "sword-driftwood": "sword", "wraps-cloth": "wraps", "bow-willow": "bow", "staff-oak": "staff", "sword-iron": "iron sword", "revolver-brass": "brass revolver", "staff-rune": "rune staff" };
const STARTERS = ["sword-driftwood", "wraps-cloth", "bow-willow", "staff-oak"], GEARED = ["sword-iron", "revolver-brass", "staff-rune"];

describe("balance pass (Part B 3, G2): scripted solo survive runs, 20 seeds per subclass", () => {
  const normal = balanceTable("survive-circle");
  const hard = balanceTable("survive-sanctum");
  it("sits in the band (combat polish 11): DPS ±25% of the median, a 3× spread of damage taken, no clear under 0.7× the median", () => {
    const b = band(normal, hard);
    expect(b.dpsLow).toBeGreaterThanOrEqual(0.75);
    expect(b.dpsHigh).toBeLessThanOrEqual(1.25);
    expect(b.spread).toBeLessThanOrEqual(3);
    expect(b.clearNormal).toBeGreaterThanOrEqual(0.7);
    expect(b.clearHard).toBeGreaterThanOrEqual(0.7);
  });
  it("every subclass clears a normal mission solo (Hold the rune circle)", () => {
    for (const r of normal) expect(r.clearRate, r.subclass).toBeGreaterThanOrEqual(0.9);
  });
  it("Warden is slightly favoured: the most reliable family on the harder run (clears, lowest health), yet not the fastest by a mile", () => {
    const fam = familyAverages(hard), warden = fam.find(f => f.family === "Warden")!;
    for (const f of fam.filter(x => x.family !== "Warden")) {
      expect(warden.clearRate, f.family).toBeGreaterThanOrEqual(f.clearRate);
      expect(warden.minHp, f.family).toBeGreaterThan(f.minHp);
    }
    const fastest = Math.min(...fam.map(f => f.medianClear));
    expect(warden.medianClear).toBeLessThan(fastest * 1.6); // strong solo fighters, not just survivors
    expect(warden.medianClear).toBeGreaterThan(fastest * 0.7); // …and not a steamroller
  });
  const elder = elderTable();
  it("zone 1's mini-boss takes 1.5–2.5 minutes for the median subclass with its starter weapon, and every subclass can beat it", () => {
    expect(median(elder.map(r => r.medianMinutes))).toBeGreaterThanOrEqual(1.5);
    expect(median(elder.map(r => r.medianMinutes))).toBeLessThanOrEqual(2.5);
    for (const r of elder) expect(r.clearRate, r.subclass).toBeGreaterThanOrEqual(0.7);
    for (const k of STARTERS) { expect(bossMinutes(k, "elder-thorn-crab"), k).toBeGreaterThanOrEqual(1.5); expect(bossMinutes(k, "elder-thorn-crab"), k).toBeLessThanOrEqual(2.5); }
  });
  it("writes specs/evidence/combat-b/balance.md when asked (WRITE_BALANCE=1)", () => {
    if (!process.env.WRITE_BALANCE) return;
    const b = band(normal, hard), x = (n: number) => `${n.toFixed(2)}×`;
    writeFileSync(join(__dirname, "../../../../specs/evidence/combat-b/balance.md"), [
      "# Combat balance: scripted solo runs (G2, combat polish 11)",
      "",
      "Generated by `web/lib/game/combat/balance.test.ts` (`WRITE_BALANCE=1 npx vitest run lib/game/combat/balance.test.ts`). Every subclass at level 10 with its family stat preset, the starter weapon (of the five the gate grants) that scales with its family's stat, the kit's suggestion where one does, and the default loadout (signature, its two own abilities, the family's second). The bot closes to its weapon's range and holds (no kiting), dodges 60% of the telegraphs aimed at it (the ruins dodge: the village dash's burst with i-frames), uses an ability when it helps, and draws runes at about 80% (one in ten fizzles, one in ten empowered). Same encounter tick and ability system as the ruins (`encounter.ts`, `abilities.ts`), open ground, 20 seeds per row, 240 s limit, every roll seeded.",
      "",
      "## The band (combat polish 11), with starter weapons",
      "",
      "| Target | Before (combat B) | Now |",
      "|---|---|---|",
      `| Normal-mission DPS within ±25% of the median | 0.64–1.49× (Transmuter 20, Monk 47) | ${x(b.dpsLow)}–${x(b.dpsHigh)} |`,
      `| Sanctum damage taken per minute within a 3× spread | 14× (Illusionist 23, Monk 331) | ${x(b.spread)} (${Math.round(Math.min(...hard.map(r => r.takenPerMin)))}–${Math.round(Math.max(...hard.map(r => r.takenPerMin)))}) |`,
      `| No clear under 0.7× the median (normal, sanctum) | 0.63×, 0.64× (Monk 12 s vs 19; Necromancer and Summoner 67 s vs 105) | ${x(b.clearNormal)}, ${x(b.clearHard)} |`,
      `| The guardian in about 4–6 minutes | sword 6.5, bow 9.2, staff 11.5 min | ${STARTERS.map(k => `${WEAPONS_NAME[k]} ${bossMinutes(k).toFixed(1)}`).join(", ")} min |`,
      "",
      `The guardian is the content pass's measure (\`bossMinutes\` in \`balance.ts\`): level 10, all 27 points in the weapon's stat, landing half the time, one hit in ten a crit. With tier 2+ gear: ${GEARED.map(k => `${WEAPONS_NAME[k]} ${bossMinutes(k).toFixed(1)}`).join(", ")} min.`,
      "",
      "What changed is data only (`lib/game/combat/data.ts`, `lib/combat/kits.ts`, the guardian in `lib/combat/content.ts` with its seed migration `20261001070514_guardian_balance_seed`):",
      "",
      "- Weapons: driftwood sword 0.42 → 0.45 s, oak staff 0.75 → 0.5 s with a faster bolt (11 → 15 u/s), cloth wraps 0.32 → 0.42 s.",
      "- The temple: books 2.6 → 4.4 u/s with a 3 u lunge at ×1.3 damage (17); golems 1.6 → 2.8 u/s, the slam ×0.41 (9) with a 1.6 s recover. The pressure that only melee stood in now reaches the back line.",
      "- The guardian: 1800 → 1700 HP, armor 9 → 7.",
      "- Vanguard: Iron Body guard 0.35 for 4 s → 0.45 for 6 s; War Cry guard 0.15 for 6 s → 0.45 for 8 s; Shield Counter blocks 0.4 (0.2 without a buckler) for 1 s every 15 s (was 0.8 for 1.5 s every 8 s); Bulwark 6% → 1%; Blood Lunge leaves a 0.3 guard for 2.5 s.",
      "- Arcane: Firebolt 1.3 → 1.6 every 2.5 s (was 3); Frost Nova holds 2 s (was 1.5); Mirror Bolts 0.8 → 1.05 every 3 s (was 4); Mass Confusion 4 → 2 s; Decoy Step slips back 2.5 u (was 4) and its phantom lasts 3 s (was 5); Monster Aspect +40% damage (was +20%); Fox Stride 1.3 → 1.7.",
      "- Ranger: Smoke Step distracts 0.5 s (was 2) and slips back 2 u (was 5).",
      "- Warden: +25% max health on all four; Holy Beam 2.2 → 2.9; Thorn Lash 1.1 → 1.5; Radiant Shield 0.45 every 10 s (was 0.35 every 14).",
      "- Summons: spirit wisp 0.55 → 0.38, fox 0.6 → 0.4, shade 0.8 → 0.55, bone wisp 0.55 → 0.45, the tome's wisp 0.6 → 0.85, the bulwark crab 180 → 400 health.",
      "",
      "## Zone 1 mobs (2026-10-02, specs/classes/design-sheet.md \"Mobs, zone 1\")",
      "",
      "The outskirts' mobs got their behaviours (fox dens flank and pounce in turn, crabs turn a front shell to you, mushrooms lob spores that leave poison, wisps bolt and blink, pollen sprites swarm and burst into slowing pollen) and the rune circle's waves now bring a fox den of three, a mushroom, a crab and a pollen cloud of eight, then a crab, a fox and a wisp. The bot circles a crab's shell to its flank and steps out of puddles and pollen. With today's kits the band above still holds; nothing in the kits changed.",
      "",
      "The elder thorn crab, zone 1's mini-boss (shell closed, cracked at 60%, enraged at 25%), is tuned to 1450 HP, 20 damage, leash 24 (was 300 HP, 16 damage: a 20-second fight). By the content pass's measure (level 10, all 27 points in the weapon's stat, landing on its flank half the time, one hit in ten a crit): " + STARTERS.map(k => `${WEAPONS_NAME[k]} ${bossMinutes(k, "elder-thorn-crab").toFixed(1)}`).join(", ") + " min; tier 2+ " + GEARED.map(k => `${WEAPONS_NAME[k]} ${bossMinutes(k, "elder-thorn-crab").toFixed(1)}`).join(", ") + " min. Against the bot, every subclass alone (20 seeds, 400 s limit):",
      "",
      "| Subclass | Family | Starter weapon | Beaten | Median time | Deaths | Lowest HP (avg) |",
      "|---|---|---|---|---|---|---|",
      ...elder.map(r => `| ${r.subclass} | ${r.family} | ${r.weapon} | ${pct(r.clearRate)} | ${Number.isNaN(r.medianMinutes) ? "–" : `${r.medianMinutes.toFixed(1)} min`} | ${r.deaths} | ${pct(r.minHp)} |`),
      "",
      `Median of the subclasses: ${median(elder.map(r => r.medianMinutes)).toFixed(1)} min. The Summoner's quick fight is its bulwark crab: it draws the elder's front, so its back is open the whole time.`,
      "",
      "## Normal mission: Hold the rune circle (outer wild, 3 waves, level 5 enemies)",
      "",
      table(normal),
      "",
      families(normal),
      "",
      "## Harder reference: Sanctum watch (inner temple, 4 waves of books and golems, levels 10–12)",
      "",
      table(hard),
      "",
      families(hard),
      "",
      "DPS is damage dealt (weapon, abilities and summons) over the run's length; damage taken is after guard, blocks and shields (heals don't count against it). The numbers are the starting balance; tune after the member playtest.",
      "",
    ].join("\n"));
  });
});
