import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { balanceRowV2, bandV2, bossMinutesV2, runV2, signatureWeapon, V2_TARGETS, type BalanceRowV2 } from "./balance";

/** The harness can measure a v2 kit (design sheet §3): the dev kit stands in until the family waves land theirs. */
describe("the v2 balance harness (§3): ult cadence, ult share, roles, mastery 1 vs 20, a scripted guardian fight", () => {
  const seeds = 6;
  const normal = balanceRowV2("demo", "survive-circle", 1, seeds), hard = balanceRowV2("demo", "survive-sanctum", 1, seeds), top = balanceRowV2("demo", "survive-circle", 20, seeds);
  it("holds the tier-1 signature weapon and clears a normal mission", () => {
    expect(signatureWeapon("demo")).toBe("staff-oak");
    expect(normal.clearRate).toBeGreaterThan(0.8);
    expect(normal.dps).toBeGreaterThan(0);
  });
  it("measures the ult: it fills on the sanctum run and lands a share of the damage", () => {
    expect(Number.isFinite(hard.ultFill)).toBe(true);
    expect(hard.ultFill).toBeGreaterThan(20);
    expect(hard.ultFill).toBeLessThan(150);
    expect(hard.ultShare).toBeGreaterThan(0);
    expect(hard.ultShare).toBeLessThan(0.5);
  });
  it("compares mastery 20 with mastery 1", () => {
    expect(top.mastery).toBe(20);
    expect(top.dps / normal.dps).toBeGreaterThan(0.5);
    expect(top.dps / normal.dps).toBeLessThan(3);
  });
  it("runs the scripted guardian fight on the same tick, with ults", () => {
    const r = runV2("demo", "boss", 1, 1, 600);
    expect(r.dealt).toBeGreaterThan(0);
    expect(r.ults).toBeGreaterThan(0);
    expect(bossMinutesV2("demo", 1, 1)).toBeGreaterThan(0);
  });
  it("puts rows against the band", () => {
    const row = (dps: number, taken: number, clear: number, role: string): BalanceRowV2 => ({ ...normal, dps, takenPerMin: taken, medianClear: clear, role, subclass: `${role}${dps}` });
    const b = bandV2([row(30, 10, 60, "damage"), row(25, 10, 70, "tank")], [row(20, 30, 90, "damage"), row(18, 10, 100, "tank")]);
    expect(b.dpsHigh).toBeCloseTo(30 / 27.5);
    expect(b.spread).toBeCloseTo(3);
    expect(b.roles.map(r => r.role)).toEqual(["damage", "tank"]);
    expect(V2_TARGETS.ultFillSanctum).toEqual([60, 90]);
  });
  it("writes specs/evidence/classes/K0-balance.md when asked (WRITE_BALANCE=1)", () => {
    if (!process.env.WRITE_BALANCE) return;
    const f = (r: BalanceRowV2) => `| ${r.subclass} | ${r.role} | ${r.mastery} | ${r.weapon} | ${Math.round(r.clearRate * 100)}% | ${Math.round(r.medianClear)} s | ${r.dps.toFixed(1)} | ${Math.round(r.takenPerMin)} | ${Number.isFinite(r.ultFill) ? `${Math.round(r.ultFill)} s` : "–"} | ${Math.round(r.ultShare * 100)}% |`;
    writeFileSync(join(__dirname, "../../../../specs/evidence/classes/K0-balance.md"), [
      "# Classes v2 harness, wave 0 (the dev kit)", "",
      "Generated by `web/lib/game/combat/balanceV2.test.ts` (`WRITE_BALANCE=1`). The dev-only demo kit through the v2 bot (design sheet §3): the tier-1 signature weapon, level 10 and the family preset, keys pressed through the input layer, movement riders met on 30% of casts, the ult fired at a full meter on two or more enemies or the boss. 6 seeds a row. It measures; it doesn't balance (the demo kit is a placeholder). Family waves add their kits' rows here and pin the band (`bandV2`, `V2_TARGETS`).", "",
      "| Kit | Role | Mastery | Weapon | Cleared | Median clear | DPS | Taken / min | Ult fill (median) | Ult share |", "|---|---|---|---|---|---|---|---|---|---|",
      f(normal), f(top), f(hard), "",
      `Rows 1–2: Hold the rune circle at mastery 1 and 20 (DPS ×${(top.dps / normal.dps).toFixed(2)}); row 3: Sanctum watch at mastery 1. The scripted guardian fight: ${bossMinutesV2("demo", 1, 4).toFixed(1)} min median (10 = never fell in 10 min).`, "",
    ].join("\n"));
  });
});
