// AUTO-GENERATED (loop wake 22, 2026-07-24) by the all-fish import pass.
// 59 dump species beyond the core roster. Names/zones/rarities from ACNH
// data (unknown romaji get prettified names + river/uncommon defaults —
// rename freely). All models raw (GAME_CALIBRATION at render), icons
// generic until the icon batch replaces them.
import type { FishDef } from "./fishing";

const GENERIC_ICON = "/assets/acnh/icons/fish.png";

export const EXTRA_FISH: FishDef[] = [
  { key: "fish_horse_mackerel", label: "a Horse Mackerel", name: "Horse Mackerel", model: "/assets/acnh/fish/horse-mackerel.glb", rarity: "common", zone: "sea", sizeCm: [20, 40], raw: true, icon: GENERIC_ICON, move: { speed: 0.22, accel: 0.9, jitter: 0.006, dartChance: 0.1, dartMul: 1.8, retargetMs: 1800 } },
  { key: "fish_angelfish", label: "an Angelfish", name: "Angelfish", model: "/assets/acnh/fish/angelfish.glb", rarity: "uncommon", zone: "river", sizeCm: [8, 12], raw: true, icon: GENERIC_ICON, move: { speed: 0.28, accel: 1.15, jitter: 0.008, dartChance: 0.15, dartMul: 1.95, retargetMs: 1500 } },
  { key: "fish_anchovy", label: "an Anchovy", name: "Anchovy", model: "/assets/acnh/fish/anchovy.glb", rarity: "common", zone: "sea", sizeCm: [10, 15], raw: true, icon: GENERIC_ICON, move: { speed: 0.22, accel: 0.9, jitter: 0.006, dartChance: 0.1, dartMul: 1.8, retargetMs: 1800 }, when: (h) => h >= 6 && h < 18, whenLabel: "day (6-18h)" },
  { key: "fish_arowana", label: "an Arowana", name: "Arowana", model: "/assets/acnh/fish/arowana.glb", rarity: "epic", zone: "river", sizeCm: [60, 90], raw: true, icon: GENERIC_ICON, move: { speed: 0.35, accel: 1.65, jitter: 0.008, dartChance: 0.28, dartMul: 2.4, retargetMs: 1200 }, when: (h) => h >= 20 || h < 4, whenLabel: "night (20-4h)" },
  { key: "fish_betta", label: "a Betta", name: "Betta", model: "/assets/acnh/fish/betta.glb", rarity: "uncommon", zone: "river", sizeCm: [6, 8], raw: true, icon: GENERIC_ICON, move: { speed: 0.28, accel: 1.15, jitter: 0.008, dartChance: 0.15, dartMul: 1.95, retargetMs: 1500 }, when: (h) => h >= 6 && h < 18, whenLabel: "day (6-18h)" },
  { key: "fish_football_fish", label: "a Football Fish", name: "Football Fish", model: "/assets/acnh/fish/football-fish.glb", rarity: "rare", zone: "sea", sizeCm: [30, 60], raw: true, icon: GENERIC_ICON, move: { speed: 0.33, accel: 1.5, jitter: 0.008, dartChance: 0.22, dartMul: 2.2, retargetMs: 1300 }, when: (h) => h >= 20 || h < 4, whenLabel: "night (20-4h)" },
  { key: "fish_butterfly_fish", label: "a Butterfly Fish", name: "Butterfly Fish", model: "/assets/acnh/fish/butterfly-fish.glb", rarity: "uncommon", zone: "sea", sizeCm: [10, 15], raw: true, icon: GENERIC_ICON, move: { speed: 0.28, accel: 1.15, jitter: 0.008, dartChance: 0.15, dartMul: 1.95, retargetMs: 1500 } },
  { key: "fish_pop_eyed_goldfish", label: "a Pop-eyed Goldfish", name: "Pop-eyed Goldfish", model: "/assets/acnh/fish/pop-eyed-goldfish.glb", rarity: "uncommon", zone: "river", sizeCm: [8, 12], raw: true, icon: GENERIC_ICON, move: { speed: 0.28, accel: 1.15, jitter: 0.008, dartChance: 0.15, dartMul: 1.95, retargetMs: 1500 } },
  { key: "fish_barreleye", label: "a Barreleye", name: "Barreleye", model: "/assets/acnh/fish/barreleye.glb", rarity: "rare", zone: "sea", sizeCm: [10, 15], raw: true, icon: GENERIC_ICON, move: { speed: 0.33, accel: 1.5, jitter: 0.008, dartChance: 0.22, dartMul: 2.2, retargetMs: 1300 }, when: (h) => h >= 20 || h < 4, whenLabel: "night (20-4h)" },
  { key: "fish_doctor_fish", label: "a Doctor Fish", name: "Doctor Fish", model: "/assets/acnh/fish/doctor-fish.glb", rarity: "uncommon", zone: "river", sizeCm: [15, 25], raw: true, icon: GENERIC_ICON, move: { speed: 0.28, accel: 1.15, jitter: 0.008, dartChance: 0.15, dartMul: 1.95, retargetMs: 1500 } },
  { key: "fish_dorado", label: "a Dorado", name: "Dorado", model: "/assets/acnh/fish/dorado.glb", rarity: "epic", zone: "river", sizeCm: [70, 100], raw: true, icon: GENERIC_ICON, move: { speed: 0.35, accel: 1.65, jitter: 0.008, dartChance: 0.28, dartMul: 2.4, retargetMs: 1200 }, when: (h) => h >= 6 && h < 18, whenLabel: "day (6-18h)" },
  { key: "fish_freshwater_goby", label: "a Freshwater Goby", name: "Freshwater Goby", model: "/assets/acnh/fish/freshwater-goby.glb", rarity: "common", zone: "river", sizeCm: [10, 15], raw: true, icon: GENERIC_ICON, move: { speed: 0.22, accel: 0.9, jitter: 0.006, dartChance: 0.1, dartMul: 1.8, retargetMs: 1800 }, when: (h) => h >= 20 || h < 4, whenLabel: "night (20-4h)" },
  { key: "fish_ray", label: "a Ray", name: "Ray", model: "/assets/acnh/fish/ray.glb", rarity: "rare", zone: "sea", sizeCm: [100, 200], raw: true, icon: GENERIC_ICON, move: { speed: 0.33, accel: 1.5, jitter: 0.008, dartChance: 0.22, dartMul: 2.2, retargetMs: 1300 }, when: (h) => h >= 6 && h < 18, whenLabel: "day (6-18h)" },
  { key: "fish_bichir", label: "a Bichir", name: "Bichir", model: "/assets/acnh/fish/bichir.glb", rarity: "rare", zone: "river", sizeCm: [40, 70], raw: true, icon: GENERIC_ICON, move: { speed: 0.33, accel: 1.5, jitter: 0.008, dartChance: 0.22, dartMul: 2.2, retargetMs: 1300 }, when: (h) => h >= 20 || h < 4, whenLabel: "night (20-4h)" },
  { key: "fish_blowfish", label: "a Blowfish", name: "Blowfish", model: "/assets/acnh/fish/blowfish.glb", rarity: "uncommon", zone: "sea", sizeCm: [20, 40], raw: true, icon: GENERIC_ICON, move: { speed: 0.28, accel: 1.15, jitter: 0.008, dartChance: 0.15, dartMul: 1.95, retargetMs: 1500 }, when: (h) => h >= 20 || h < 4, whenLabel: "night (20-4h)" },
  { key: "fish_guppy", label: "a Guppy", name: "Guppy", model: "/assets/acnh/fish/guppy.glb", rarity: "common", zone: "river", sizeCm: [3, 5], raw: true, icon: GENERIC_ICON, move: { speed: 0.22, accel: 0.9, jitter: 0.006, dartChance: 0.1, dartMul: 1.8, retargetMs: 1800 }, when: (h) => h >= 6 && h < 18, whenLabel: "day (6-18h)" },
  { key: "fish_ribbon_eel", label: "a Ribbon Eel", name: "Ribbon Eel", model: "/assets/acnh/fish/ribbon-eel.glb", rarity: "uncommon", zone: "sea", sizeCm: [60, 100], raw: true, icon: GENERIC_ICON, move: { speed: 0.28, accel: 1.15, jitter: 0.008, dartChance: 0.15, dartMul: 1.95, retargetMs: 1500 } },
  { key: "fish_porcupine_fish", label: "a Porcupine Fish", name: "Porcupine Fish", model: "/assets/acnh/fish/porcupine-fish.glb", rarity: "uncommon", zone: "sea", sizeCm: [20, 35], raw: true, icon: GENERIC_ICON, move: { speed: 0.28, accel: 1.15, jitter: 0.008, dartChance: 0.15, dartMul: 1.95, retargetMs: 1500 } },
  { key: "fish_olive_flounder", label: "an Olive Flounder", name: "Olive Flounder", model: "/assets/acnh/fish/olive-flounder.glb", rarity: "uncommon", zone: "sea", sizeCm: [40, 80], raw: true, icon: GENERIC_ICON, move: { speed: 0.28, accel: 1.15, jitter: 0.008, dartChance: 0.15, dartMul: 1.95, retargetMs: 1500 } },
  { key: "fish_squid", label: "a Squid", name: "Squid", model: "/assets/acnh/fish/squid.glb", rarity: "common", zone: "sea", sizeCm: [20, 40], raw: true, icon: GENERIC_ICON, move: { speed: 0.22, accel: 0.9, jitter: 0.006, dartChance: 0.1, dartMul: 1.8, retargetMs: 1800 } },
  { key: "fish_barred_knifejaw", label: "a Barred Knifejaw", name: "Barred Knifejaw", model: "/assets/acnh/fish/barred-knifejaw.glb", rarity: "uncommon", zone: "sea", sizeCm: [30, 50], raw: true, icon: GENERIC_ICON, move: { speed: 0.28, accel: 1.15, jitter: 0.008, dartChance: 0.15, dartMul: 1.95, retargetMs: 1500 } },
  { key: "fish_whale_shark", label: "a Whale Shark", name: "Whale Shark", model: "/assets/acnh/fish/whale-shark.glb", rarity: "legendary", zone: "sea", sizeCm: [400, 800], raw: true, icon: GENERIC_ICON, move: { speed: 0.41, accel: 2.05, jitter: 0.011, dartChance: 0.31, dartMul: 2.35, retargetMs: 1000 } },
  { key: "fish_frog", label: "a Frog", name: "Frog", model: "/assets/acnh/fish/frog.glb", rarity: "common", zone: "river", sizeCm: [5, 10], raw: true, icon: GENERIC_ICON, move: { speed: 0.22, accel: 0.9, jitter: 0.006, dartChance: 0.1, dartMul: 1.8, retargetMs: 1800 } },
  { key: "fish_blue_marlin", label: "a Blue Marlin", name: "Blue Marlin", model: "/assets/acnh/fish/blue-marlin.glb", rarity: "epic", zone: "sea", sizeCm: [200, 350], raw: true, icon: GENERIC_ICON, move: { speed: 0.35, accel: 1.65, jitter: 0.008, dartChance: 0.28, dartMul: 2.4, retargetMs: 1200 } },
  { key: "fish_snapping_turtle", label: "a Snapping Turtle", name: "Snapping Turtle", model: "/assets/acnh/fish/snapping-turtle.glb", rarity: "rare", zone: "river", sizeCm: [20, 35], raw: true, icon: GENERIC_ICON, move: { speed: 0.33, accel: 1.5, jitter: 0.008, dartChance: 0.22, dartMul: 2.2, retargetMs: 1300 }, when: (h) => h >= 20 || h < 4, whenLabel: "night (20-4h)" },
  { key: "fish_dab", label: "a Dab", name: "Dab", model: "/assets/acnh/fish/dab.glb", rarity: "common", zone: "sea", sizeCm: [25, 45], raw: true, icon: GENERIC_ICON, move: { speed: 0.22, accel: 0.9, jitter: 0.006, dartChance: 0.1, dartMul: 1.8, retargetMs: 1800 } },
  { key: "fish_suckerfish", label: "a Suckerfish", name: "Suckerfish", model: "/assets/acnh/fish/suckerfish.glb", rarity: "uncommon", zone: "sea", sizeCm: [30, 60], raw: true, icon: GENERIC_ICON, move: { speed: 0.28, accel: 1.15, jitter: 0.008, dartChance: 0.15, dartMul: 1.95, retargetMs: 1500 } },
  { key: "fish_clown_fish", label: "a Clown Fish", name: "Clown Fish", model: "/assets/acnh/fish/clown-fish.glb", rarity: "common", zone: "sea", sizeCm: [8, 12], raw: true, icon: GENERIC_ICON, move: { speed: 0.22, accel: 0.9, jitter: 0.006, dartChance: 0.1, dartMul: 1.8, retargetMs: 1800 } },
  { key: "fish_sea_butterfly", label: "a Sea Butterfly", name: "Sea Butterfly", model: "/assets/acnh/fish/sea-butterfly.glb", rarity: "common", zone: "sea", sizeCm: [2, 4], raw: true, icon: GENERIC_ICON, move: { speed: 0.22, accel: 0.9, jitter: 0.006, dartChance: 0.1, dartMul: 1.8, retargetMs: 1800 } },
  { key: "fish_tuna", label: "a Tuna", name: "Tuna", model: "/assets/acnh/fish/tuna.glb", rarity: "epic", zone: "sea", sizeCm: [150, 250], raw: true, icon: GENERIC_ICON, move: { speed: 0.35, accel: 1.65, jitter: 0.008, dartChance: 0.28, dartMul: 2.4, retargetMs: 1200 } },
  { key: "fish_ocean_sunfish", label: "an Ocean Sunfish", name: "Ocean Sunfish", model: "/assets/acnh/fish/ocean-sunfish.glb", rarity: "epic", zone: "sea", sizeCm: [150, 300], raw: true, icon: GENERIC_ICON, move: { speed: 0.35, accel: 1.65, jitter: 0.008, dartChance: 0.28, dartMul: 2.4, retargetMs: 1200 } },
  { key: "fish_zebra_turkeyfish", label: "a Zebra Turkeyfish", name: "Zebra Turkeyfish", model: "/assets/acnh/fish/zebra-turkeyfish.glb", rarity: "uncommon", zone: "sea", sizeCm: [25, 40], raw: true, icon: GENERIC_ICON, move: { speed: 0.28, accel: 1.15, jitter: 0.008, dartChance: 0.15, dartMul: 1.95, retargetMs: 1500 } },
  { key: "fish_surgeonfish", label: "a Surgeonfish", name: "Surgeonfish", model: "/assets/acnh/fish/surgeonfish.glb", rarity: "common", zone: "sea", sizeCm: [15, 25], raw: true, icon: GENERIC_ICON, move: { speed: 0.22, accel: 0.9, jitter: 0.006, dartChance: 0.1, dartMul: 1.8, retargetMs: 1800 } },
  { key: "fish_napoleonfish", label: "a Napoleonfish", name: "Napoleonfish", model: "/assets/acnh/fish/napoleonfish.glb", rarity: "epic", zone: "sea", sizeCm: [100, 180], raw: true, icon: GENERIC_ICON, move: { speed: 0.35, accel: 1.65, jitter: 0.008, dartChance: 0.28, dartMul: 2.4, retargetMs: 1200 }, when: (h) => h >= 6 && h < 18, whenLabel: "day (6-18h)" },
  { key: "fish_neon_tetra", label: "a Neon Tetra", name: "Neon Tetra", model: "/assets/acnh/fish/neon-tetra.glb", rarity: "common", zone: "river", sizeCm: [3, 4], raw: true, icon: GENERIC_ICON, move: { speed: 0.22, accel: 0.9, jitter: 0.006, dartChance: 0.1, dartMul: 1.8, retargetMs: 1800 }, when: (h) => h >= 6 && h < 18, whenLabel: "day (6-18h)" },
  { key: "fish_saw_shark", label: "a Saw Shark", name: "Saw Shark", model: "/assets/acnh/fish/saw-shark.glb", rarity: "legendary", zone: "sea", sizeCm: [120, 200], raw: true, icon: GENERIC_ICON, move: { speed: 0.41, accel: 2.05, jitter: 0.011, dartChance: 0.31, dartMul: 2.35, retargetMs: 1000 }, when: (h) => h >= 20 || h < 4, whenLabel: "night (20-4h)" },
  { key: "fish_char", label: "a Char", name: "Char", model: "/assets/acnh/fish/char.glb", rarity: "rare", zone: "river", sizeCm: [40, 60], raw: true, icon: GENERIC_ICON, move: { speed: 0.33, accel: 1.5, jitter: 0.008, dartChance: 0.22, dartMul: 2.2, retargetMs: 1300 } },
  { key: "fish_tadpole", label: "a Tadpole", name: "Tadpole", model: "/assets/acnh/fish/tadpole.glb", rarity: "common", zone: "river", sizeCm: [3, 5], raw: true, icon: GENERIC_ICON, move: { speed: 0.22, accel: 0.9, jitter: 0.006, dartChance: 0.1, dartMul: 1.8, retargetMs: 1800 } },
  { key: "fish_pike", label: "a Pike", name: "Pike", model: "/assets/acnh/fish/pike.glb", rarity: "rare", zone: "river", sizeCm: [50, 90], raw: true, icon: GENERIC_ICON, move: { speed: 0.33, accel: 1.5, jitter: 0.008, dartChance: 0.22, dartMul: 2.2, retargetMs: 1300 } },
  { key: "fish_piranha", label: "a Piranha", name: "Piranha", model: "/assets/acnh/fish/piranha.glb", rarity: "rare", zone: "river", sizeCm: [25, 40], raw: true, icon: GENERIC_ICON, move: { speed: 0.33, accel: 1.5, jitter: 0.008, dartChance: 0.22, dartMul: 2.2, retargetMs: 1300 }, when: (h) => h >= 6 && h < 18, whenLabel: "day (6-18h)" },
  { key: "fish_ranchu_goldfish", label: "a Ranchu Goldfish", name: "Ranchu Goldfish", model: "/assets/acnh/fish/ranchu-goldfish.glb", rarity: "uncommon", zone: "river", sizeCm: [10, 15], raw: true, icon: GENERIC_ICON, move: { speed: 0.28, accel: 1.15, jitter: 0.008, dartChance: 0.15, dartMul: 1.95, retargetMs: 1500 } },
  { key: "fish_giant_trevally", label: "a Giant Trevally", name: "Giant Trevally", model: "/assets/acnh/fish/giant-trevally.glb", rarity: "epic", zone: "sea", sizeCm: [80, 150], raw: true, icon: GENERIC_ICON, move: { speed: 0.35, accel: 1.65, jitter: 0.008, dartChance: 0.28, dartMul: 2.4, retargetMs: 1200 } },
  { key: "fish_oarfish", label: "an Oarfish", name: "Oarfish", model: "/assets/acnh/fish/oarfish.glb", rarity: "legendary", zone: "sea", sizeCm: [300, 500], raw: true, icon: GENERIC_ICON, move: { speed: 0.41, accel: 2.05, jitter: 0.011, dartChance: 0.31, dartMul: 2.35, retargetMs: 1000 } },
  { key: "fish_great_white_shark", label: "a Great White Shark", name: "Great White Shark", model: "/assets/acnh/fish/great-white-shark.glb", rarity: "legendary", zone: "sea", sizeCm: [300, 500], raw: true, icon: GENERIC_ICON, move: { speed: 0.41, accel: 2.05, jitter: 0.011, dartChance: 0.31, dartMul: 2.35, retargetMs: 1000 } },
  // Naming pass (David ruling, 2026-07-24): the 15 romaji placeholders
  // resolved to their real species — names/zones/rarities/sizes set, GLB
  // files renamed to match. Keys renamed too (pre-launch, no member data).
  { key: "fish_mahi_mahi", label: "a Mahi-Mahi", name: "Mahi-Mahi", model: "/assets/acnh/fish/mahi-mahi.glb", rarity: "rare", zone: "sea", sizeCm: [80, 140], raw: true, icon: GENERIC_ICON, move: { speed: 0.33, accel: 1.5, jitter: 0.008, dartChance: 0.22, dartMul: 2.2, retargetMs: 1300 } },
  { key: "fish_hammerhead_shark", label: "a Hammerhead Shark", name: "Hammerhead Shark", model: "/assets/acnh/fish/hammerhead-shark.glb", rarity: "legendary", zone: "sea", sizeCm: [180, 350], raw: true, icon: GENERIC_ICON, move: { speed: 0.41, accel: 2.05, jitter: 0.011, dartChance: 0.31, dartMul: 2.35, retargetMs: 1000 } },
  { key: "fish_coelacanth", label: "a Coelacanth", name: "Coelacanth", model: "/assets/acnh/fish/coelacanth.glb", rarity: "legendary", zone: "sea", sizeCm: [120, 180], raw: true, icon: GENERIC_ICON, move: { speed: 0.41, accel: 2.05, jitter: 0.011, dartChance: 0.31, dartMul: 2.35, retargetMs: 1000 }, when: (h, w) => (h >= 20 || h < 4) && w === "rain", whenLabel: "rainy nights" },
  { key: "fish_soft_shelled_turtle", label: "a Soft-shelled Turtle", name: "Soft-shelled Turtle", model: "/assets/acnh/fish/soft-shelled-turtle.glb", rarity: "uncommon", zone: "river", sizeCm: [20, 35], raw: true, icon: GENERIC_ICON, move: { speed: 0.28, accel: 1.15, jitter: 0.008, dartChance: 0.15, dartMul: 1.95, retargetMs: 1500 } },
  { key: "fish_sea_bass", label: "a Sea Bass", name: "Sea Bass", model: "/assets/acnh/fish/sea-bass.glb", rarity: "common", zone: "sea", sizeCm: [50, 90], raw: true, icon: GENERIC_ICON, move: { speed: 0.22, accel: 0.9, jitter: 0.006, dartChance: 0.1, dartMul: 1.8, retargetMs: 1800 } },
  { key: "fish_mitten_crab", label: "a Mitten Crab", name: "Mitten Crab", model: "/assets/acnh/fish/mitten-crab.glb", rarity: "uncommon", zone: "river", sizeCm: [10, 18], raw: true, icon: GENERIC_ICON, move: { speed: 0.28, accel: 1.15, jitter: 0.008, dartChance: 0.15, dartMul: 1.95, retargetMs: 1500 } },
  { key: "fish_red_snapper", label: "a Red Snapper", name: "Red Snapper", model: "/assets/acnh/fish/red-snapper.glb", rarity: "uncommon", zone: "sea", sizeCm: [30, 60], raw: true, icon: GENERIC_ICON, move: { speed: 0.28, accel: 1.15, jitter: 0.008, dartChance: 0.15, dartMul: 1.95, retargetMs: 1500 } },
  { key: "fish_bitterling", label: "a Bitterling", name: "Bitterling", model: "/assets/acnh/fish/bitterling.glb", rarity: "common", zone: "river", sizeCm: [5, 10], raw: true, icon: GENERIC_ICON, move: { speed: 0.22, accel: 0.9, jitter: 0.006, dartChance: 0.1, dartMul: 1.8, retargetMs: 1800 } },
  { key: "fish_seahorse", label: "a Seahorse", name: "Seahorse", model: "/assets/acnh/fish/seahorse.glb", rarity: "uncommon", zone: "sea", sizeCm: [3, 6], raw: true, icon: GENERIC_ICON, move: { speed: 0.16, accel: 0.65, jitter: 0.01, dartChance: 0.08, dartMul: 1.5, retargetMs: 2100 } },
  { key: "fish_tilapia", label: "a Tilapia", name: "Tilapia", model: "/assets/acnh/fish/tilapia.glb", rarity: "uncommon", zone: "river", sizeCm: [25, 40], raw: true, icon: GENERIC_ICON, move: { speed: 0.28, accel: 1.15, jitter: 0.008, dartChance: 0.15, dartMul: 1.95, retargetMs: 1500 } },
  { key: "fish_sturgeon", label: "a Sturgeon", name: "Sturgeon", model: "/assets/acnh/fish/sturgeon.glb", rarity: "legendary", zone: "river", sizeCm: [100, 200], raw: true, icon: GENERIC_ICON, move: { speed: 0.41, accel: 2.05, jitter: 0.011, dartChance: 0.31, dartMul: 2.35, retargetMs: 1000 } },
  { key: "fish_moray_eel", label: "a Moray Eel", name: "Moray Eel", model: "/assets/acnh/fish/moray-eel.glb", rarity: "uncommon", zone: "sea", sizeCm: [60, 100], raw: true, icon: GENERIC_ICON, move: { speed: 0.28, accel: 1.15, jitter: 0.008, dartChance: 0.15, dartMul: 1.95, retargetMs: 1500 } },
  { key: "fish_yamame_trout", label: "a Yamame Trout", name: "Yamame Trout", model: "/assets/acnh/fish/yamame-trout.glb", rarity: "uncommon", zone: "river", sizeCm: [20, 35], raw: true, icon: GENERIC_ICON, move: { speed: 0.28, accel: 1.15, jitter: 0.008, dartChance: 0.15, dartMul: 1.95, retargetMs: 1500 } },
  { key: "fish_yellow_perch", label: "a Yellow Perch", name: "Yellow Perch", model: "/assets/acnh/fish/yellow-perch.glb", rarity: "common", zone: "river", sizeCm: [20, 30], raw: true, icon: GENERIC_ICON, move: { speed: 0.22, accel: 0.9, jitter: 0.006, dartChance: 0.1, dartMul: 1.8, retargetMs: 1800 } },
  { key: "fish_crayfish", label: "a Crayfish", name: "Crayfish", model: "/assets/acnh/fish/crayfish.glb", rarity: "common", zone: "river", sizeCm: [5, 12], raw: true, icon: GENERIC_ICON, move: { speed: 0.22, accel: 0.9, jitter: 0.006, dartChance: 0.1, dartMul: 1.8, retargetMs: 1800 } },
];
