import { describe, it, expect } from "vitest";
import doc from "../../data/island-map.json";
import {
  parseIslandMap,
  levelAt,
  surfaceAt,
  isVoid,
  isRiver,
  isRamp,
  needsCliff,
  cliffPieceFor,
  rampDir,
  rampRun,
  ORTHOGONAL,
  inBounds,
  CLIFF_LEVELS,
  type IslandMap,
  type IslandMapDoc,
} from "./grid";

/**
 * The shipped map, checked the way the player will experience it.
 *
 * `grid.test.ts` proves the functions are right. Nothing proved the DATA was,
 * and it drifted: `author-elevation.mjs` reads `island-map.json`, mutates it and
 * writes it back, so its own output is its next input. Surfaces are not
 * recomputed between runs, and ramp cells accumulated against levels that had
 * moved -- 21 of them, 12 orphaned, invisible because the renderer quietly falls
 * back to a grass quad when a ramp has nothing to climb.
 *
 * These are the same checks `/lab/map` shows live in its panel, so a map edited
 * by hand and a map generated by the script are held to one standard.
 */

const { map } = parseIslandMap(doc as IslandMapDoc);

/** River and sea are not standable. Everything else on the island is. */
function walkable(m: IslandMap, x: number, z: number): boolean {
  if (!inBounds(m, x, z)) return false;
  const s = surfaceAt(m, x, z);
  return !isVoid(s) && !isRiver(s);
}

function forEachCell(fn: (x: number, z: number) => void) {
  for (let z = 0; z < map.depth; z++) for (let x = 0; x < map.width; x++) fn(x, z);
}

describe("island-map.json", () => {
  it("every walkable cell is reachable on foot", () => {
    // The one property nothing else surfaces. With cliffs as hard barriers a
    // terrace can be drawn perfectly and simply be unreachable, and the only
    // symptom is a player who cannot get there.
    let seed: [number, number] | null = null;
    let total = 0;
    forEachCell((x, z) => {
      if (!walkable(map, x, z)) return;
      total++;
      if (!seed && levelAt(map, x, z) === 0) seed = [x, z];
    });
    expect(seed).not.toBeNull();

    const seen = new Uint8Array(map.width * map.depth);
    const stack: [number, number][] = [seed!];
    let reached = 0;
    while (stack.length) {
      const [x, z] = stack.pop()!;
      const i = z * map.width + x;
      if (seen[i]) continue;
      seen[i] = 1;
      reached++;
      for (const [dx, dz] of ORTHOGONAL) {
        const nx = x + dx;
        const nz = z + dz;
        if (!walkable(map, nx, nz) || seen[nz * map.width + nx]) continue;
        const drop = Math.abs(levelAt(map, nx, nz) - levelAt(map, x, z));
        // Only a ramp whose RUN resolves is a route. Keying on the surface
        // alone counts a broken ramp as a way up and reports the map more
        // connected than it is.
        const viaRamp = !!rampRun(map, nx, nz) || !!rampRun(map, x, z);
        if (drop < CLIFF_LEVELS || viaRamp) stack.push([nx, nz]);
      }
    }
    expect(reached).toBe(total);
  });

  it("every cliff cell has a kit piece to draw it", () => {
    const missing: string[] = [];
    forEachCell((x, z) => {
      if (isVoid(surfaceAt(map, x, z))) return;
      if (needsCliff(map, x, z) && !cliffPieceFor(map, x, z)) missing.push(`${x},${z}`);
    });
    expect(missing).toEqual([]);
  });

  it("no ramp is orphaned", () => {
    // An orphan renders as flat grass, so this never shows up by looking.
    const orphans: string[] = [];
    forEachCell((x, z) => {
      if (isRamp(surfaceAt(map, x, z)) && !rampDir(map, x, z)) orphans.push(`${x},${z}`);
    });
    expect(orphans).toEqual([]);
  });

  it("has no one-cell-wide walls", () => {
    // Raised ground with lower ground on both sides of an axis is a wall the
    // player cannot stand on, and it reads as a fence, not a landform.
    const walls: string[] = [];
    forEachCell((x, z) => {
      if (isVoid(surfaceAt(map, x, z))) return;
      const l = levelAt(map, x, z);
      if (l === 0) return;
      const lower = (dx: number, dz: number) =>
        walkable(map, x + dx, z + dz) && levelAt(map, x + dx, z + dz) < l;
      if ((lower(-1, 0) && lower(1, 0)) || (lower(0, -1) && lower(0, 1))) walls.push(`${x},${z}`);
    });
    expect(walls).toEqual([]);
  });

  it("stays mostly flat, with half steps rare", () => {
    // David's direction, 2026-07-29: mostly flat island, full cliffs where the
    // level changes, rare BLENDED half steps for naturalness. These bounds are
    // loose on purpose -- they catch a regeneration that changes the character
    // of the island, not one that moves a plateau by a few cells.
    const hist = new Map<number, number>();
    let land = 0;
    forEachCell((x, z) => {
      if (isVoid(surfaceAt(map, x, z))) return;
      land++;
      const l = levelAt(map, x, z);
      hist.set(l, (hist.get(l) ?? 0) + 1);
    });
    const share = (l: number) => (hist.get(l) ?? 0) / land;
    expect(share(0)).toBeGreaterThan(0.7);
    expect(share(1)).toBeLessThan(0.05);
    expect(Math.max(...hist.keys())).toBeLessThanOrEqual(CLIFF_LEVELS * 2);
  });

  it("never puts adjacent cells more than one cliff apart", () => {
    // The kit is one piece tall and does not stack, so a taller face has
    // nothing to draw it and would render as a hole.
    const bad: string[] = [];
    forEachCell((x, z) => {
      if (isVoid(surfaceAt(map, x, z))) return;
      const l = levelAt(map, x, z);
      for (const [dx, dz] of ORTHOGONAL) {
        if (!inBounds(map, x + dx, z + dz)) continue;
        const s = surfaceAt(map, x + dx, z + dz);
        const nl = isVoid(s) ? 0 : levelAt(map, x + dx, z + dz);
        if (Math.abs(l - nl) > CLIFF_LEVELS) bad.push(`${x},${z}->${x + dx},${z + dz}`);
      }
    });
    expect(bad).toEqual([]);
  });
});
